<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="0.145" timestamp="2025-03-30T23:45:02.759767-03:00" hostname="ubuntu24-B550M-AORUS-ELITE"><testcase classname="" name="tests.models.test_caminhos" time="0.000"><error message="collection failure">tests/models/test_caminhos.py:20: in &lt;module&gt;
    class TestValidacaoClassificacao:
tests/models/test_caminhos.py:23: in TestValidacaoClassificacao
    pytest.param("C:\\Users\\file.txt", True, marks=pytest.mark.windows),
.venv/lib/python3.12/site-packages/_pytest/mark/structures.py:546: in __getattr__
    warnings.warn(
E   pytest.PytestUnknownMarkWarning: Unknown pytest.mark.windows - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html</error></testcase></testsuite></testsuites>